# Generated by Django 4.2.7 on 2023-11-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(max_length=100, null=True)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(null=True)),
                ("temporary_age", models.IntegerField(null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("I", "Intersex"),
                            ("X", "Unknown"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
